### ISSUE TITLE
Todo v2

### ISSUE THREAD

**Issue by koenbok** [framer/monobase#28]
- [x] Also use transpiled code to render pages
- [x] Make sure new components are detected without restart
- [x] Use the React Context API for page contexts
- [ ] Make the html output nice (in development)
- [ ] See if we can get React Hooks to work
- [ ] Client side build error reporting (dialog on top with source)
- [ ] Great automated testing setup (project → build)
- [ ] Support mdx out of the box
- [ ] Default blog / articles setup
- [ ] Rethink component mount system (get rid of component tag)
- [ ] See if we can factor out React (webpack external)

**Comment by koenbok** [comment]
https://github.com/koenbok/monobase/compare/babel
